# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PortfolioOptimize.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17PortfolioOptimize.proto\x12\rExpertService\x1a\x1bgoogle/protobuf/empty.proto2\x13\n\x11OptimizePortfolioB\x19\xaa\x02\x16\x45xpertService.Optimizeb\x06proto3')



_OPTIMIZEPORTFOLIO = DESCRIPTOR.services_by_name['OptimizePortfolio']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\026ExpertService.Optimize'
  _OPTIMIZEPORTFOLIO._serialized_start=71
  _OPTIMIZEPORTFOLIO._serialized_end=90
# @@protoc_insertion_point(module_scope)
